# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c7faa3b397117292e3741beddec8482ddc9dcbbc88c7a191418d067de1c40062ceae252e50a282714707180e8e51700ba400e356bc223831995f5b0a28516ea5

test:
  secret_key_base: 9a026613cb3be4d88e9621edf816cec2ebeccb6a28734d4588aa93c25c3e6039013f8b3faa761f56be090b52460385bda3c327217da8899de3422bed4d94af3f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
